#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# Requirements: localhost resolves to 127.0.0.2, facebook resolves to 8.8.8.8

# Update the /etc/hosts file to configure IP resolution
sudo sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts > /dev/null
