#!/usr/bin/env bash
# Listens to the specified port

# Run the following commands to install necessary stuff:
# apt install -y netcat
# apt install telnet

# Listen on port 98 and output any received data
nc -l -p 98